name: test_api
channels:
  - defaults
  - pytorch
dependencies:
  - python = 3.10
  - pip = 25.0
  - pip:
      - clip==1.0
      - datasets==3.4.1
      - fastapi==0.115.12
      - flask==3.1.0
      - jsonify==0.5
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - networkx==3.4.2
      - numpy==2.2.4
      - nvidia-ml-py==12.570.86
      - openai==1.68.2
      - openai-clip==1.0.1
      - pandas==2.2.3
      - pillow==11.1.0
      - pynvml==12.0.0
      - requests==2.32.3
      - rpds-py==0.23.1
      - scipy==1.15.2
      - torch==2.6.0
      - torchvision==0.21.0
      - tqdm==4.67.1
